# Generated by Django 4.0.4 on 2022-06-26 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Akustiky',
            fields=[
                ('id_AkustikY', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('Nazvanie', models.CharField(max_length=50, verbose_name='Название')),
                ('Proizvoditel', models.CharField(max_length=20, verbose_name='Производитель')),
                ('potrebl_moshnost', models.IntegerField(verbose_name='Потребляемая мощность')),
                ('vihodnaya_moshnost', models.IntegerField(verbose_name='Выходная мощность')),
                ('blupup', models.CharField(max_length=20, verbose_name='Bluetooth')),
                ('wifi', models.CharField(max_length=20, verbose_name='Wifi')),
                ('Ves', models.IntegerField(verbose_name='Вес')),
                ('gabarit', models.CharField(max_length=14, verbose_name='Габариты')),
                ('dinamiky', models.IntegerField(verbose_name='Динамики')),
                ('diaazon_chastot', models.CharField(max_length=14, verbose_name='Диапазон частот')),
                ('iterfeysy', models.CharField(max_length=60, verbose_name='Интерфейсы')),
                ('oisanye', models.CharField(max_length=1000, verbose_name='Описание')),
                ('foto', models.ImageField(default='no_image.jpg', upload_to='product_image')),
                ('Cena', models.IntegerField(default=0, verbose_name='Цена')),
            ],
        ),
        migrations.CreateModel(
            name='Bytovaya_elektronika',
            fields=[
                ('id_Bytovaya_elektronika', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('Nazvanie', models.CharField(max_length=50, verbose_name='Название')),
                ('Proizvoditel', models.CharField(max_length=20, verbose_name='Производитель')),
                ('moshnost', models.IntegerField(verbose_name='Мощность')),
                ('wifi', models.CharField(max_length=20, verbose_name='Wifi')),
                ('gabarit', models.CharField(max_length=14, verbose_name='Габариты')),
                ('dinamiky', models.IntegerField(verbose_name='Динамики')),
                ('Cena', models.IntegerField(verbose_name='Цена')),
                ('oisanye', models.CharField(max_length=1000, verbose_name='Описание')),
                ('foto', models.ImageField(default='no_image.jpg', upload_to='product_image')),
            ],
        ),
        migrations.CreateModel(
            name='Dolzhnosty',
            fields=[
                ('id_dolzhnosty', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nazvanie', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Elektronika',
            fields=[
                ('id_Elektronika', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('Nazvanie', models.CharField(max_length=50, verbose_name='Название')),
                ('Proizvoditel', models.CharField(max_length=20, verbose_name='Производительность')),
                ('razmer_displeya', models.CharField(max_length=20, verbose_name='Размер дисплея')),
                ('tip_displeya', models.CharField(max_length=20, verbose_name='Тип дисплея')),
                ('cpu', models.CharField(max_length=20, verbose_name='CPU')),
                ('gpu', models.CharField(max_length=20, verbose_name='GPU')),
                ('chastota_CPU', models.CharField(max_length=20, verbose_name='Частота CPU')),
                ('tip_pamyati', models.CharField(max_length=20, verbose_name='Тип памяти')),
                ('objem_pamyaty', models.CharField(max_length=20, verbose_name='Объем памяти')),
                ('interfeysy', models.CharField(max_length=20, verbose_name='Интерфейсы')),
                ('Kamera', models.IntegerField(verbose_name='Камера')),
                ('Cena', models.IntegerField(verbose_name='Цена')),
                ('oisanye', models.CharField(max_length=1000, verbose_name='Описание')),
                ('foto', models.ImageField(default='no_image.jpg', upload_to='product_image')),
            ],
        ),
        migrations.CreateModel(
            name='Kategorii_akustika',
            fields=[
                ('id_kategoriya_aud_tehnika', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('kategoriya_aud_tehnika', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='kategoriya_bytovaya_elektronika',
            fields=[
                ('id_kategoriya_bytovaya_elektronika', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('kategoriya_bytovaya_elektronika', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Kategoriya_elektronika',
            fields=[
                ('id_kategoriya_elektronika', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nazvanie', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Kategoriya_stroy_elektronika',
            fields=[
                ('id_kategoriya_stroy_elektronika', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nazvanie', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Kategoriya_yuvelirka',
            fields=[
                ('id_kategoriya_yuvelirka', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nazvanie', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Klienty',
            fields=[
                ('id_klient', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('familiya', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('imya', models.CharField(max_length=15, verbose_name='Имя')),
                ('otchestvo', models.CharField(max_length=20, verbose_name='ОТчество')),
                ('seriya', models.IntegerField(verbose_name='Серия')),
                ('nomer', models.IntegerField(verbose_name='Номер')),
                ('telefon', models.IntegerField(verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
            ],
        ),
        migrations.CreateModel(
            name='Paroly',
            fields=[
                ('id_parolya', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('login', models.CharField(max_length=15, verbose_name='Логин')),
                ('Parol', models.CharField(max_length=10, verbose_name='Пароль')),
            ],
        ),
        migrations.CreateModel(
            name='Prochee',
            fields=[
                ('id_Prochee', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('Nazvanie', models.CharField(max_length=50, verbose_name='Название')),
                ('Proizvoditel', models.CharField(max_length=20, verbose_name='Производитель')),
                ('harakteristyki', models.CharField(max_length=1000, verbose_name='Характеристики')),
                ('Cena', models.IntegerField(verbose_name='Цена')),
                ('oisanye', models.CharField(max_length=1000, verbose_name='Описание')),
                ('foto', models.ImageField(default='no_image.jpg', upload_to='product_image')),
            ],
        ),
        migrations.CreateModel(
            name='Sostoyanie_veshi',
            fields=[
                ('id_Sostoyanie_veshi', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Sostoyanie', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Sostoyanie_zaloga',
            fields=[
                ('id_sostoyanie_zaloga', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nazvanie', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Sotrudniky',
            fields=[
                ('id_sotrudnika', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('familiya', models.CharField(max_length=30)),
                ('imya', models.CharField(max_length=15)),
                ('otchestvo', models.CharField(max_length=20)),
                ('seriya', models.IntegerField()),
                ('nomer', models.IntegerField()),
                ('adress', models.CharField(max_length=60)),
                ('telefon', models.IntegerField()),
                ('nomer_scheta', models.IntegerField()),
                ('id_dolzhnosty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.dolzhnosty')),
                ('id_parolya', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.paroly')),
            ],
        ),
        migrations.CreateModel(
            name='Stroy_elektronika',
            fields=[
                ('id_Stroy_elektronika', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('Nazvanie', models.CharField(max_length=50, verbose_name='Название')),
                ('Proizvoditel', models.CharField(max_length=20, verbose_name='Производитель')),
                ('moshnost', models.IntegerField(verbose_name='Мощность')),
                ('krutyshy_moment', models.IntegerField(verbose_name='Крутящий момент')),
                ('akkumulyator', models.IntegerField(verbose_name='Аккамулятор')),
                ('ves', models.IntegerField(verbose_name='Вес')),
                ('Cena', models.IntegerField(verbose_name='Цена')),
                ('oisanye', models.CharField(max_length=1000, verbose_name='Описание')),
                ('foto', models.ImageField(default='no_image.jpg', upload_to='product_image')),
                ('id_Sostoyanie_veshi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.sostoyanie_veshi', verbose_name='Состояние')),
                ('id_kategoriya_stroy_elektronika', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.kategoriya_stroy_elektronika', verbose_name='Категория')),
            ],
        ),
        migrations.CreateModel(
            name='Yuvelirka',
            fields=[
                ('id_Yuvelirka', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('proba', models.IntegerField(verbose_name='Проба')),
                ('ves', models.IntegerField(verbose_name='Вес')),
                ('razmer', models.CharField(max_length=20, verbose_name='Размер')),
                ('vstavka', models.CharField(max_length=20, verbose_name='Вставка')),
                ('Cena', models.IntegerField(verbose_name='Цена')),
                ('oisanye', models.CharField(max_length=1000, verbose_name='Описание')),
                ('foto', models.ImageField(default='no_image.jpg', upload_to='product_image')),
                ('id_Sostoyanie_veshi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.sostoyanie_veshi', verbose_name='Состояние')),
                ('id_kategoriya_yuvelirka', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.kategoriya_yuvelirka', verbose_name='Категория')),
            ],
        ),
        migrations.CreateModel(
            name='Zalogovye_bilety',
            fields=[
                ('id_zaloga', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Summa_zajma', models.IntegerField()),
                ('Summa_procentov', models.IntegerField()),
                ('data_nachala', models.DateField()),
                ('data_okonchaniya', models.DateField()),
                ('id_Akustiky', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.akustiky')),
                ('id_Bytovaya_elektronika', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.bytovaya_elektronika')),
                ('id_Elektronika', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.elektronika')),
                ('id_Prochee', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.prochee')),
                ('id_Stroy_elektronika', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.stroy_elektronika')),
                ('id_Yuvelirka', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.yuvelirka')),
                ('id_klient', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.klienty')),
                ('id_sostoyanie_zaloga', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.sostoyanie_zaloga')),
                ('id_sotrudnika', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.sotrudniky')),
            ],
        ),
        migrations.CreateModel(
            name='Tovarnje_cheky',
            fields=[
                ('id_tovarnje_cheky', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('Summa_pokupky', models.IntegerField(verbose_name='Сумма покупки')),
                ('id_klient', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.klienty', verbose_name='Клиент')),
            ],
        ),
        migrations.CreateModel(
            name='Rashodnjy_kassovjy_orden',
            fields=[
                ('id_rashodnjy_kassovjy_orden', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('id_klient', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.klienty')),
                ('id_sotrudnika', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.sotrudniky')),
                ('id_zaloga', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.zalogovye_bilety')),
            ],
        ),
        migrations.AddField(
            model_name='prochee',
            name='id_Sostoyanie_veshi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.sostoyanie_veshi', verbose_name='Состояние'),
        ),
        migrations.CreateModel(
            name='Korzina',
            fields=[
                ('id_Korzina', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('id_AkustikY', models.ManyToManyField(null=True, to='web.akustiky')),
                ('id_Bytovaya_elektronika', models.ManyToManyField(null=True, to='web.bytovaya_elektronika')),
                ('id_Elektronika', models.ManyToManyField(null=True, to='web.elektronika')),
                ('id_Prochee', models.ManyToManyField(null=True, to='web.prochee')),
                ('id_Stroy_elektronika', models.ManyToManyField(blank=True, null=True, related_name='targets', to='web.stroy_elektronika')),
                ('id_Yuvelirka', models.ManyToManyField(null=True, to='web.yuvelirka')),
                ('id_parolya', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.paroly')),
            ],
        ),
        migrations.AddField(
            model_name='klienty',
            name='id_parolya',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.paroly', verbose_name='Пароль'),
        ),
        migrations.AddField(
            model_name='elektronika',
            name='id_Sostoyanie_veshi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.sostoyanie_veshi', verbose_name='Состояние'),
        ),
        migrations.AddField(
            model_name='elektronika',
            name='id_kategoriya_elektronika',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.kategoriya_elektronika', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='bytovaya_elektronika',
            name='id_Sostoyanie_veshi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.sostoyanie_veshi', verbose_name='Состояние'),
        ),
        migrations.AddField(
            model_name='bytovaya_elektronika',
            name='id_kategoriya_bytovaya_elektronika',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.kategoriya_bytovaya_elektronika', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='akustiky',
            name='id_Sostoyanie_veshi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.sostoyanie_veshi', verbose_name='Состояние'),
        ),
        migrations.AddField(
            model_name='akustiky',
            name='id_kategoriya_aud_tehnika',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.kategorii_akustika', verbose_name='Категория'),
        ),
    ]
