# Generated by Django 4.0.4 on 2022-05-09 09:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategorii_akustika',
            fields=[
                ('id_kategoriya_aud_tehnika', models.UUIDField(default=uuid.uuid4, help_text='pohuy', primary_key=True, serialize=False)),
                ('kategoriya_aud_tehnika', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Akustika',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_audio_tehnika', models.IntegerField()),
                ('otrebl_moshnost', models.IntegerField()),
                ('vihodnaya_moshnost', models.IntegerField()),
                ('blupup', models.CharField(max_length=20)),
                ('wifi', models.CharField(max_length=20)),
                ('Ves', models.IntegerField()),
                ('id_kategoriya_aud_tehnika', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.kategorii_akustika')),
            ],
        ),
    ]
