# Generated by Django 4.0.4 on 2022-05-09 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_akustiki_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Akustiky',
            fields=[
                ('id_AkustikY', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Nazvanie', models.CharField(max_length=50)),
                ('Proizvoditel', models.CharField(max_length=20)),
                ('potrebl_moshnost', models.IntegerField()),
                ('vihodnaya_moshnost', models.IntegerField()),
                ('blupup', models.CharField(max_length=20)),
                ('wifi', models.CharField(max_length=20)),
                ('Ves', models.IntegerField()),
                ('gabarit', models.CharField(max_length=14)),
                ('dinamiky', models.IntegerField()),
                ('diaazon_chastot', models.CharField(max_length=14)),
                ('iterfeysy', models.CharField(max_length=60)),
                ('oisanye', models.CharField(max_length=1000)),
                ('foto', models.ImageField(upload_to='')),
                ('id_kategoriya_aud_tehnika', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.kategorii_akustika')),
            ],
        ),
        migrations.CreateModel(
            name='Bytovaya_elektronika',
            fields=[
                ('id_Bytovaya_elektronika', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Nazvanie', models.CharField(max_length=50)),
                ('Proizvoditel', models.CharField(max_length=20)),
                ('moshnost', models.IntegerField()),
                ('wifi', models.CharField(max_length=20)),
                ('gabarit', models.CharField(max_length=14)),
                ('dinamiky', models.IntegerField()),
                ('Cena', models.IntegerField()),
                ('oisanye', models.CharField(max_length=1000)),
                ('foto', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Dolzhnosty',
            fields=[
                ('id_dolzhnosty', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nazvanie', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Elektronika',
            fields=[
                ('id_Elektronika', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Nazvanie', models.CharField(max_length=50)),
                ('Proizvoditel', models.CharField(max_length=20)),
                ('razmer_displeya', models.CharField(max_length=20)),
                ('tip_displeya', models.CharField(max_length=20)),
                ('cpu', models.CharField(max_length=20)),
                ('gpu', models.CharField(max_length=20)),
                ('chastota_CPU', models.CharField(max_length=20)),
                ('tip_pamyati', models.CharField(max_length=20)),
                ('objem_pamyaty', models.CharField(max_length=20)),
                ('interfeysy', models.CharField(max_length=20)),
                ('Kamera', models.IntegerField()),
                ('Cena', models.IntegerField()),
                ('oisanye', models.CharField(max_length=1000)),
                ('foto', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='kategoriya_bytovaya_elektronika',
            fields=[
                ('id_kategoriya_bytovaya_elektronika', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('kategoriya_bytovaya_elektronika', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Kategoriya_elektronika',
            fields=[
                ('id_kategoriya_elektronika', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nazvanie', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Kategoriya_stroy_elektronika',
            fields=[
                ('id_kategoriya_stroy_elektronika', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nazvanie', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Kategoriya_yuvelirka',
            fields=[
                ('id_kategoriya_yuvelirka', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nazvanie', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Klienty',
            fields=[
                ('id_klient', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('familiya', models.CharField(max_length=30)),
                ('imya', models.CharField(max_length=15)),
                ('otchestvo', models.CharField(max_length=20)),
                ('seriya', models.IntegerField()),
                ('nomer', models.IntegerField()),
                ('telefon', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Paroly',
            fields=[
                ('id_parolya', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('login', models.CharField(max_length=15)),
                ('Parol', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Prochee',
            fields=[
                ('id_Prochee', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Nazvanie', models.CharField(max_length=50)),
                ('Proizvoditel', models.CharField(max_length=20)),
                ('harakteristyki', models.CharField(max_length=1000)),
                ('Cena', models.IntegerField()),
                ('oisanye', models.CharField(max_length=1000)),
                ('foto', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Rashodnjy_kassovjy_orden',
            fields=[
                ('id_rashodnjy_kassovjy_orden', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('id_klient', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.klienty')),
            ],
        ),
        migrations.CreateModel(
            name='Sostoyanie_zaloga',
            fields=[
                ('id_sostoyanie_zaloga', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nazvanie', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Sotrudniky',
            fields=[
                ('id_sotrudnika', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('familiya', models.CharField(max_length=30)),
                ('imya', models.CharField(max_length=15)),
                ('otchestvo', models.CharField(max_length=20)),
                ('seriya', models.IntegerField()),
                ('nomer', models.IntegerField()),
                ('adress', models.CharField(max_length=60)),
                ('telefon', models.IntegerField()),
                ('nomer_scheta', models.IntegerField()),
                ('id_dolzhnosty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.dolzhnosty')),
                ('id_parolya', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.paroly')),
            ],
        ),
        migrations.CreateModel(
            name='Stroy_elektronika',
            fields=[
                ('id_Stroy_elektronika', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Nazvanie', models.CharField(max_length=50)),
                ('Proizvoditel', models.CharField(max_length=20)),
                ('moshnost', models.IntegerField()),
                ('krutyshy_moment', models.IntegerField()),
                ('akkumulyator', models.IntegerField()),
                ('ves', models.IntegerField()),
                ('Cena', models.IntegerField()),
                ('oisanye', models.CharField(max_length=1000)),
                ('foto', models.ImageField(upload_to='')),
                ('id_kategoriya_stroy_elektronika', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.kategoriya_stroy_elektronika')),
            ],
        ),
        migrations.CreateModel(
            name='Tovarnje_cheky',
            fields=[
                ('id_tovarnje_cheky', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Summa_pokupky', models.IntegerField()),
                ('id_klient', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.klienty')),
            ],
        ),
        migrations.CreateModel(
            name='Yuvelirka',
            fields=[
                ('id_Yuvelirka', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('proba', models.IntegerField()),
                ('ves', models.IntegerField()),
                ('razmer', models.CharField(max_length=20)),
                ('vstavka', models.CharField(max_length=20)),
                ('Cena', models.IntegerField()),
                ('oisanye', models.CharField(max_length=1000)),
                ('foto', models.ImageField(upload_to='')),
                ('id_kategoriya_yuvelirka', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.kategoriya_yuvelirka')),
            ],
        ),
        migrations.CreateModel(
            name='Zalogovye_bilety',
            fields=[
                ('id_zaloga', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Summa_zajma', models.IntegerField()),
                ('Summa_procentov', models.IntegerField()),
                ('data_nachala', models.DateField()),
                ('data_okonchaniya', models.DateField()),
                ('id_Akustiky', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.akustiky')),
                ('id_Bytovaya_elektronika', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.bytovaya_elektronika')),
                ('id_Elektronika', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.elektronika')),
                ('id_Prochee', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.prochee')),
                ('id_Stroy_elektronika', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.stroy_elektronika')),
                ('id_Yuvelirka', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.yuvelirka')),
                ('id_klient', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.klienty')),
                ('id_sostoyanie_zaloga', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.sostoyanie_zaloga')),
                ('id_sotrudnika', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.sotrudniky')),
            ],
        ),
        migrations.DeleteModel(
            name='Akustiki',
        ),
        migrations.AddField(
            model_name='rashodnjy_kassovjy_orden',
            name='id_sotrudnika',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.sotrudniky'),
        ),
        migrations.AddField(
            model_name='rashodnjy_kassovjy_orden',
            name='id_zaloga',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.zalogovye_bilety'),
        ),
        migrations.AddField(
            model_name='klienty',
            name='id_parolya',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.paroly'),
        ),
        migrations.AddField(
            model_name='elektronika',
            name='id_kategoriya_elektronika',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.kategoriya_elektronika'),
        ),
        migrations.AddField(
            model_name='bytovaya_elektronika',
            name='id_kategoriya_bytovaya_elektronika',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.kategoriya_bytovaya_elektronika'),
        ),
    ]
