# Generated by Django 4.0.4 on 2022-05-09 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_akustiky_bytovaya_elektronika_dolzhnosty_elektronika_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='akustiky',
            name='foto',
            field=models.ImageField(upload_to='product_image'),
        ),
    ]
