# Generated by Django 4.0.4 on 2022-05-09 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_akustiky_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='akustiky',
            name='foto',
            field=models.ImageField(default='no_image.jpg', upload_to='product_image'),
        ),
    ]
