# Generated by Django 4.0.4 on 2022-05-09 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alter_akustiky_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='akustiky',
            name='Cena',
            field=models.IntegerField(default=0),
        ),
    ]
