# Generated by Django 4.0.4 on 2022-05-10 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_akustiky_cena'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bytovaya_elektronika',
            name='foto',
            field=models.ImageField(default='no_image.jpg', upload_to='product_image'),
        ),
        migrations.AlterField(
            model_name='elektronika',
            name='foto',
            field=models.ImageField(default='no_image.jpg', upload_to='product_image'),
        ),
        migrations.AlterField(
            model_name='prochee',
            name='foto',
            field=models.ImageField(default='no_image.jpg', upload_to='product_image'),
        ),
        migrations.AlterField(
            model_name='stroy_elektronika',
            name='foto',
            field=models.ImageField(default='no_image.jpg', upload_to='product_image'),
        ),
        migrations.AlterField(
            model_name='yuvelirka',
            name='foto',
            field=models.ImageField(default='no_image.jpg', upload_to='product_image'),
        ),
    ]
