# Generated by Django 4.0.4 on 2022-05-13 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_alter_bytovaya_elektronika_foto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Korzina',
            fields=[
                ('id_Korzina', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('id_Akustiky', models.ManyToManyField(null=True, to='web.akustiky')),
                ('id_Bytovaya_elektronika', models.ManyToManyField(null=True, to='web.bytovaya_elektronika')),
                ('id_Elektronika', models.ManyToManyField(null=True, to='web.elektronika')),
                ('id_Prochee', models.ManyToManyField(null=True, to='web.prochee')),
                ('id_Stroy_elektronika', models.ManyToManyField(null=True, to='web.stroy_elektronika')),
                ('id_Yuvelirka', models.ManyToManyField(null=True, to='web.yuvelirka')),
                ('id_klient', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.klienty')),
            ],
        ),
    ]
