# Generated by Django 4.0.4 on 2022-05-13 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_korzina'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='korzina',
            name='id_klient',
        ),
        migrations.AddField(
            model_name='korzina',
            name='id_parolya',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.paroly'),
        ),
    ]
