# Generated by Django 4.0.4 on 2022-05-13 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_remove_korzina_id_klient_korzina_id_parolya'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='korzina',
            name='id_Akustiky',
        ),
        migrations.AddField(
            model_name='korzina',
            name='id_Akustiky',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.akustiky'),
        ),
        migrations.RemoveField(
            model_name='korzina',
            name='id_Bytovaya_elektronika',
        ),
        migrations.AddField(
            model_name='korzina',
            name='id_Bytovaya_elektronika',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.bytovaya_elektronika'),
        ),
        migrations.RemoveField(
            model_name='korzina',
            name='id_Elektronika',
        ),
        migrations.AddField(
            model_name='korzina',
            name='id_Elektronika',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.elektronika'),
        ),
        migrations.RemoveField(
            model_name='korzina',
            name='id_Prochee',
        ),
        migrations.AddField(
            model_name='korzina',
            name='id_Prochee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.prochee'),
        ),
        migrations.RemoveField(
            model_name='korzina',
            name='id_Stroy_elektronika',
        ),
        migrations.AddField(
            model_name='korzina',
            name='id_Stroy_elektronika',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.stroy_elektronika'),
        ),
        migrations.RemoveField(
            model_name='korzina',
            name='id_Yuvelirka',
        ),
        migrations.AddField(
            model_name='korzina',
            name='id_Yuvelirka',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.yuvelirka'),
        ),
    ]
