# Generated by Django 4.0.4 on 2022-05-13 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_remove_korzina_id_akustiky_korzina_id_akustiky_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='korzina',
            name='id_Akustiky',
        ),
        migrations.AddField(
            model_name='korzina',
            name='id_Akustiky',
            field=models.ManyToManyField(null=True, to='web.akustiky'),
        ),
        migrations.RemoveField(
            model_name='korzina',
            name='id_Bytovaya_elektronika',
        ),
        migrations.AddField(
            model_name='korzina',
            name='id_Bytovaya_elektronika',
            field=models.ManyToManyField(null=True, to='web.bytovaya_elektronika'),
        ),
        migrations.RemoveField(
            model_name='korzina',
            name='id_Elektronika',
        ),
        migrations.AddField(
            model_name='korzina',
            name='id_Elektronika',
            field=models.ManyToManyField(null=True, to='web.elektronika'),
        ),
        migrations.RemoveField(
            model_name='korzina',
            name='id_Prochee',
        ),
        migrations.AddField(
            model_name='korzina',
            name='id_Prochee',
            field=models.ManyToManyField(null=True, to='web.prochee'),
        ),
        migrations.RemoveField(
            model_name='korzina',
            name='id_Stroy_elektronika',
        ),
        migrations.AddField(
            model_name='korzina',
            name='id_Stroy_elektronika',
            field=models.ManyToManyField(null=True, to='web.stroy_elektronika'),
        ),
        migrations.RemoveField(
            model_name='korzina',
            name='id_Yuvelirka',
        ),
        migrations.AddField(
            model_name='korzina',
            name='id_Yuvelirka',
            field=models.ManyToManyField(null=True, to='web.yuvelirka'),
        ),
    ]
