# Generated by Django 4.0.4 on 2022-05-13 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_remove_korzina_id_akustiky_korzina_id_akustiky_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='korzina',
            name='id_Bytovaya_elektronika',
        ),
        migrations.AddField(
            model_name='korzina',
            name='id_Bytovaya_elektronika',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.bytovaya_elektronika'),
        ),
    ]
