# Generated by Django 4.0.4 on 2022-05-13 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_remove_korzina_id_bytovaya_elektronika_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='korzina',
            name='id_Akustiky',
        ),
        migrations.AddField(
            model_name='korzina',
            name='id_AkustikY',
            field=models.ManyToManyField(null=True, to='web.akustiky'),
        ),
    ]
