# Generated by Django 4.0.4 on 2022-05-14 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_remove_korzina_id_akustiky_korzina_id_akustiky'),
    ]

    operations = [
        migrations.AlterField(
            model_name='korzina',
            name='id_Stroy_elektronika',
            field=models.ManyToManyField(null=True, related_name='targets', to='web.stroy_elektronika'),
        ),
    ]
