# Generated by Django 4.0.4 on 2022-05-14 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_alter_korzina_id_stroy_elektronika'),
    ]

    operations = [
        migrations.AlterField(
            model_name='korzina',
            name='id_Stroy_elektronika',
            field=models.ManyToManyField(blank=True, null=True, related_name='targets', to='web.stroy_elektronika'),
        ),
    ]
