# Generated by Django 4.0.4 on 2022-05-14 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_alter_korzina_id_stroy_elektronika'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sostoyanie_veshi',
            fields=[
                ('id_Sostoyanie_veshi', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Sostoyanie', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='akustiky',
            name='id_Sostoyanie_veshi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.sostoyanie_veshi'),
        ),
        migrations.AddField(
            model_name='bytovaya_elektronika',
            name='id_Sostoyanie_veshi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.sostoyanie_veshi'),
        ),
        migrations.AddField(
            model_name='elektronika',
            name='id_Sostoyanie_veshi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.sostoyanie_veshi'),
        ),
        migrations.AddField(
            model_name='prochee',
            name='id_Sostoyanie_veshi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.sostoyanie_veshi'),
        ),
        migrations.AddField(
            model_name='stroy_elektronika',
            name='id_Sostoyanie_veshi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.sostoyanie_veshi'),
        ),
        migrations.AddField(
            model_name='yuvelirka',
            name='id_Sostoyanie_veshi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.sostoyanie_veshi'),
        ),
    ]
